// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * Body_collections-create_run
 */
export type Body_collections_create_run = {
    /**
     * File
     */
    file: Blob | File;
    /**
     * Report Date
     *
     * ISO date (YYYY-MM-DD) to anchor overdue/ageing calculations to. Defaults to the workbook's own configured report date (settings.REPORT_DATE) if omitted.
     */
    report_date?: string | null;
};

/**
 * Body_login-login_access_token
 */
export type Body_login_login_access_token = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * ExceptionOut
 *
 * `cause`/`impact`/`suggested_fix`/`owner`/`auto_fixable` come from
 * the rule's shared `RunRuleExplanation` (Phase 7), joined by
 * `rule_code` -- not stored per exception row. `auto_fixable` is
 * always `False` -- see `ai/roles/exception_explainer.py`.
 */
export type ExceptionOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Rule Code
     */
    rule_code: string;
    /**
     * Category
     */
    category: string;
    /**
     * Message
     */
    message: string;
    /**
     * Severity
     */
    severity: string;
    /**
     * Invoice Id
     */
    invoice_id: string | null;
    /**
     * Payment Id
     */
    payment_id: string | null;
    /**
     * Customer Id
     */
    customer_id: string | null;
    /**
     * Detail Json
     */
    detail_json: {
        [key: string]: unknown;
    } | null;
    /**
     * Cause
     */
    cause: string | null;
    /**
     * Impact
     */
    impact: string | null;
    /**
     * Suggested Fix
     */
    suggested_fix: string | null;
    /**
     * Owner
     */
    owner: string | null;
    /**
     * Auto Fixable
     */
    auto_fixable: boolean;
    /**
     * Explanation Source
     */
    explanation_source: string | null;
};

/**
 * ExceptionsOut
 */
export type ExceptionsOut = {
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Data
     */
    data: Array<ExceptionOut>;
    /**
     * Count
     */
    count: number;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * InvoicePositionOut
 */
export type InvoicePositionOut = {
    /**
     * Invoice Id
     */
    invoice_id: string;
    /**
     * Customer Id
     */
    customer_id: string;
    /**
     * Region
     */
    region: string | null;
    /**
     * Due Date
     */
    due_date: string | null;
    /**
     * Outstanding
     */
    outstanding: string;
    /**
     * Is Overdue
     */
    is_overdue: boolean;
    /**
     * Days Overdue
     */
    days_overdue: number;
    /**
     * Ageing Bucket
     */
    ageing_bucket: string | null;
};

/**
 * ItemCreate
 */
export type ItemCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemPublic
 */
export type ItemPublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * ItemUpdate
 */
export type ItemUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemsPublic
 */
export type ItemsPublic = {
    /**
     * Data
     */
    data: Array<ItemPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * OverdueOut
 */
export type OverdueOut = {
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Data
     */
    data: Array<InvoicePositionOut>;
    /**
     * Count
     */
    count: number;
    /**
     * Total Outstanding
     */
    total_outstanding: string;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * RegionBreakdownOut
 */
export type RegionBreakdownOut = {
    /**
     * Region
     */
    region: string;
    /**
     * Outstanding
     */
    outstanding: string;
    /**
     * Overdue Count
     */
    overdue_count: number;
};

/**
 * RegionsOut
 */
export type RegionsOut = {
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Data
     */
    data: Array<RegionBreakdownOut>;
    /**
     * Heaviest Region
     */
    heaviest_region: string | null;
};

/**
 * RunEventOut
 */
export type RunEventOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Ts
     */
    ts: string;
    /**
     * Stage
     */
    stage: string;
    /**
     * Level
     */
    level: string;
    /**
     * Code
     */
    code: string;
    /**
     * Message
     */
    message: string;
    /**
     * Detail Json
     */
    detail_json: {
        [key: string]: unknown;
    } | null;
};

/**
 * RunEventsOut
 */
export type RunEventsOut = {
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Data
     */
    data: Array<RunEventOut>;
};

/**
 * RunOut
 */
export type RunOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Source Filename
     */
    source_filename: string;
    /**
     * Report Date
     */
    report_date: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Completed At
     */
    completed_at: string | null;
    /**
     * Error Code
     */
    error_code: string | null;
    /**
     * Error Message
     */
    error_message: string | null;
    /**
     * Customer Count
     */
    customer_count: number | null;
    /**
     * Invoice Count
     */
    invoice_count: number | null;
    /**
     * Payment Count
     */
    payment_count: number | null;
    /**
     * Overdue Count
     */
    overdue_count: number | null;
    /**
     * Total Outstanding
     */
    total_outstanding: string | null;
    /**
     * Exception Count
     */
    exception_count: number | null;
    /**
     * Has Download
     */
    readonly has_download: boolean;
};

/**
 * RunsOut
 */
export type RunsOut = {
    /**
     * Data
     */
    data: Array<RunOut>;
    /**
     * Count
     */
    count: number;
};

/**
 * SendEmailRequest
 */
export type SendEmailRequest = {
    /**
     * To
     */
    to: string;
};

/**
 * SendEmailResponse
 */
export type SendEmailResponse = {
    /**
     * Sent
     */
    sent: boolean;
    /**
     * Message
     */
    message: string;
};

/**
 * SummaryOut
 *
 * The "blocked payload" QA_PREP.md Q7 describes: the rate, both
 * denominators, the threshold, and the count -- whichever way the gate
 * went. `status` is "PASSED"/"BLOCKED" (or "FAILED" if the run never
 * reached the gate).
 */
export type SummaryOut = {
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Report Date
     */
    report_date: string;
    /**
     * Customer Count
     */
    customer_count: number | null;
    /**
     * Invoice Count
     */
    invoice_count: number | null;
    /**
     * Payment Count
     */
    payment_count: number | null;
    /**
     * Overdue Count
     */
    overdue_count: number | null;
    /**
     * Total Outstanding
     */
    total_outstanding: string | null;
    /**
     * Exception Count
     */
    exception_count: number | null;
    /**
     * Gate Threshold
     */
    gate_threshold: string | null;
    /**
     * Exception Row Rate
     */
    exception_row_rate: string | null;
    /**
     * Distinct Invoices Affected
     */
    distinct_invoices_affected: number | null;
    /**
     * Distinct Invoice Rate
     */
    distinct_invoice_rate: string | null;
    /**
     * Narrative
     */
    narrative: string | null;
    /**
     * Summary Source
     */
    summary_source: string | null;
    /**
     * By Region
     */
    by_region: Array<RegionBreakdownOut>;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * RunOut
 */
export type RunOutWritable = {
    /**
     * Id
     */
    id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Source Filename
     */
    source_filename: string;
    /**
     * Report Date
     */
    report_date: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Completed At
     */
    completed_at: string | null;
    /**
     * Error Code
     */
    error_code: string | null;
    /**
     * Error Message
     */
    error_message: string | null;
    /**
     * Customer Count
     */
    customer_count: number | null;
    /**
     * Invoice Count
     */
    invoice_count: number | null;
    /**
     * Payment Count
     */
    payment_count: number | null;
    /**
     * Overdue Count
     */
    overdue_count: number | null;
    /**
     * Total Outstanding
     */
    total_outstanding: string | null;
    /**
     * Exception Count
     */
    exception_count: number | null;
};

/**
 * RunsOut
 */
export type RunsOutWritable = {
    /**
     * Data
     */
    data: Array<RunOutWritable>;
    /**
     * Count
     */
    count: number;
};

export type loginLoginAccessTokenData = {
    body: Body_login_login_access_token;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type loginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginLoginAccessTokenError = loginLoginAccessTokenErrors[keyof loginLoginAccessTokenErrors];

export type loginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type loginLoginAccessTokenResponse = loginLoginAccessTokenResponses[keyof loginLoginAccessTokenResponses];

export type loginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type loginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type loginTestTokenResponse = loginTestTokenResponses[keyof loginTestTokenResponses];

export type loginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type loginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordError = loginRecoverPasswordErrors[keyof loginRecoverPasswordErrors];

export type loginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginRecoverPasswordResponse = loginRecoverPasswordResponses[keyof loginRecoverPasswordResponses];

export type loginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type loginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginResetPasswordError = loginResetPasswordErrors[keyof loginResetPasswordErrors];

export type loginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginResetPasswordResponse = loginResetPasswordResponses[keyof loginResetPasswordResponses];

export type loginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type loginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordHtmlContentError = loginRecoverPasswordHtmlContentErrors[keyof loginRecoverPasswordHtmlContentErrors];

export type loginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type loginRecoverPasswordHtmlContentResponse = loginRecoverPasswordHtmlContentResponses[keyof loginRecoverPasswordHtmlContentResponses];

export type usersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type usersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUsersError = usersReadUsersErrors[keyof usersReadUsersErrors];

export type usersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type usersReadUsersResponse = usersReadUsersResponses[keyof usersReadUsersResponses];

export type usersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type usersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersCreateUserError = usersCreateUserErrors[keyof usersCreateUserErrors];

export type usersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersCreateUserResponse = usersCreateUserResponses[keyof usersCreateUserResponses];

export type usersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserMeResponse = usersDeleteUserMeResponses[keyof usersDeleteUserMeResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserMeError = usersUpdateUserMeErrors[keyof usersUpdateUserMeErrors];

export type usersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserMeResponse = usersUpdateUserMeResponses[keyof usersUpdateUserMeResponses];

export type usersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type usersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdatePasswordMeError = usersUpdatePasswordMeErrors[keyof usersUpdatePasswordMeErrors];

export type usersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersUpdatePasswordMeResponse = usersUpdatePasswordMeResponses[keyof usersUpdatePasswordMeResponses];

export type usersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type usersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersRegisterUserError = usersRegisterUserErrors[keyof usersRegisterUserErrors];

export type usersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersRegisterUserResponse = usersRegisterUserResponses[keyof usersRegisterUserResponses];

export type usersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersDeleteUserError = usersDeleteUserErrors[keyof usersDeleteUserErrors];

export type usersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserResponse = usersDeleteUserResponses[keyof usersDeleteUserResponses];

export type usersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserByIdError = usersReadUserByIdErrors[keyof usersReadUserByIdErrors];

export type usersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserByIdResponse = usersReadUserByIdResponses[keyof usersReadUserByIdResponses];

export type usersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserError = usersUpdateUserErrors[keyof usersUpdateUserErrors];

export type usersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserResponse = usersUpdateUserResponses[keyof usersUpdateUserResponses];

export type utilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type utilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type utilsTestEmailError = utilsTestEmailErrors[keyof utilsTestEmailErrors];

export type utilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type utilsTestEmailResponse = utilsTestEmailResponses[keyof utilsTestEmailResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];

export type itemsReadItemsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/items/';
};

export type itemsReadItemsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsReadItemsError = itemsReadItemsErrors[keyof itemsReadItemsErrors];

export type itemsReadItemsResponses = {
    /**
     * Successful Response
     */
    200: ItemsPublic;
};

export type itemsReadItemsResponse = itemsReadItemsResponses[keyof itemsReadItemsResponses];

export type itemsCreateItemData = {
    body: ItemCreate;
    path?: never;
    query?: never;
    url: '/api/v1/items/';
};

export type itemsCreateItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsCreateItemError = itemsCreateItemErrors[keyof itemsCreateItemErrors];

export type itemsCreateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsCreateItemResponse = itemsCreateItemResponses[keyof itemsCreateItemResponses];

export type itemsDeleteItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsDeleteItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsDeleteItemError = itemsDeleteItemErrors[keyof itemsDeleteItemErrors];

export type itemsDeleteItemResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type itemsDeleteItemResponse = itemsDeleteItemResponses[keyof itemsDeleteItemResponses];

export type itemsReadItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsReadItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsReadItemError = itemsReadItemErrors[keyof itemsReadItemErrors];

export type itemsReadItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsReadItemResponse = itemsReadItemResponses[keyof itemsReadItemResponses];

export type itemsUpdateItemData = {
    body: ItemUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsUpdateItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsUpdateItemError = itemsUpdateItemErrors[keyof itemsUpdateItemErrors];

export type itemsUpdateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsUpdateItemResponse = itemsUpdateItemResponses[keyof itemsUpdateItemResponses];

export type collectionsListRunsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/collections/runs/';
};

export type collectionsListRunsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type collectionsListRunsError = collectionsListRunsErrors[keyof collectionsListRunsErrors];

export type collectionsListRunsResponses = {
    /**
     * Successful Response
     */
    200: RunsOut;
};

export type collectionsListRunsResponse = collectionsListRunsResponses[keyof collectionsListRunsResponses];

export type collectionsCreateRunData = {
    body: Body_collections_create_run;
    path?: never;
    query?: never;
    url: '/api/v1/collections/runs/';
};

export type collectionsCreateRunErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type collectionsCreateRunError = collectionsCreateRunErrors[keyof collectionsCreateRunErrors];

export type collectionsCreateRunResponses = {
    /**
     * Successful Response
     */
    200: RunOut;
};

export type collectionsCreateRunResponse = collectionsCreateRunResponses[keyof collectionsCreateRunResponses];

export type collectionsGetRunData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/collections/runs/{run_id}';
};

export type collectionsGetRunErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type collectionsGetRunError = collectionsGetRunErrors[keyof collectionsGetRunErrors];

export type collectionsGetRunResponses = {
    /**
     * Successful Response
     */
    200: RunOut;
};

export type collectionsGetRunResponse = collectionsGetRunResponses[keyof collectionsGetRunResponses];

export type collectionsDownloadRunFileData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/collections/runs/{run_id}/download';
};

export type collectionsDownloadRunFileErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type collectionsDownloadRunFileError = collectionsDownloadRunFileErrors[keyof collectionsDownloadRunFileErrors];

export type collectionsDownloadRunFileResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type collectionsSendRunEmailData = {
    body: SendEmailRequest;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/collections/runs/{run_id}/send-email';
};

export type collectionsSendRunEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type collectionsSendRunEmailError = collectionsSendRunEmailErrors[keyof collectionsSendRunEmailErrors];

export type collectionsSendRunEmailResponses = {
    /**
     * Successful Response
     */
    200: SendEmailResponse;
};

export type collectionsSendRunEmailResponse = collectionsSendRunEmailResponses[keyof collectionsSendRunEmailResponses];

export type collectionsGetOverdueData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Run Id
         */
        run_id: string;
    };
    url: '/api/v1/collections/overdue/';
};

export type collectionsGetOverdueErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type collectionsGetOverdueError = collectionsGetOverdueErrors[keyof collectionsGetOverdueErrors];

export type collectionsGetOverdueResponses = {
    /**
     * Successful Response
     */
    200: OverdueOut;
};

export type collectionsGetOverdueResponse = collectionsGetOverdueResponses[keyof collectionsGetOverdueResponses];

export type collectionsGetExceptionsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Run Id
         */
        run_id: string;
        /**
         * Rule Code
         */
        rule_code?: string | null;
        /**
         * Severity
         */
        severity?: string | null;
    };
    url: '/api/v1/collections/exceptions/';
};

export type collectionsGetExceptionsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type collectionsGetExceptionsError = collectionsGetExceptionsErrors[keyof collectionsGetExceptionsErrors];

export type collectionsGetExceptionsResponses = {
    /**
     * Successful Response
     */
    200: ExceptionsOut;
};

export type collectionsGetExceptionsResponse = collectionsGetExceptionsResponses[keyof collectionsGetExceptionsResponses];

export type collectionsGetRegionsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Run Id
         */
        run_id: string;
    };
    url: '/api/v1/collections/regions/';
};

export type collectionsGetRegionsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type collectionsGetRegionsError = collectionsGetRegionsErrors[keyof collectionsGetRegionsErrors];

export type collectionsGetRegionsResponses = {
    /**
     * Successful Response
     */
    200: RegionsOut;
};

export type collectionsGetRegionsResponse = collectionsGetRegionsResponses[keyof collectionsGetRegionsResponses];

export type collectionsGetSummaryData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Run Id
         */
        run_id: string;
    };
    url: '/api/v1/collections/summary/';
};

export type collectionsGetSummaryErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type collectionsGetSummaryError = collectionsGetSummaryErrors[keyof collectionsGetSummaryErrors];

export type collectionsGetSummaryResponses = {
    /**
     * Successful Response
     */
    200: SummaryOut;
};

export type collectionsGetSummaryResponse = collectionsGetSummaryResponses[keyof collectionsGetSummaryResponses];

export type collectionsGetRunEventsData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/collections/run-log/{run_id}/events';
};

export type collectionsGetRunEventsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type collectionsGetRunEventsError = collectionsGetRunEventsErrors[keyof collectionsGetRunEventsErrors];

export type collectionsGetRunEventsResponses = {
    /**
     * Successful Response
     */
    200: RunEventsOut;
};

export type collectionsGetRunEventsResponse = collectionsGetRunEventsResponses[keyof collectionsGetRunEventsResponses];

export type privateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type privateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type privateCreateUserError = privateCreateUserErrors[keyof privateCreateUserErrors];

export type privateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type privateCreateUserResponse = privateCreateUserResponses[keyof privateCreateUserResponses];
