"""add collections run, run_event, run_exception, run_invoice_position tables

Revision ID: 3c6653dbe726
Revises: fe56fa70289e
Create Date: 2026-08-31 17:12:53.209478

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3c6653dbe726'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('source_filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_count', sa.Integer(), nullable=True),
    sa.Column('invoice_count', sa.Integer(), nullable=True),
    sa.Column('payment_count', sa.Integer(), nullable=True),
    sa.Column('overdue_count', sa.Integer(), nullable=True),
    sa.Column('total_outstanding', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('exception_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_run_status'), 'collections_run', ['status'], unique=False)
    op.create_table('collections_run_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detail_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['collections_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_run_event_level'), 'collections_run_event', ['level'], unique=False)
    op.create_index(op.f('ix_collections_run_event_run_id'), 'collections_run_event', ['run_id'], unique=False)
    op.create_index(op.f('ix_collections_run_event_stage'), 'collections_run_event', ['stage'], unique=False)
    op.create_table('collections_run_exception',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('rule_code', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('invoice_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('payment_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('detail_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['collections_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_run_exception_customer_id'), 'collections_run_exception', ['customer_id'], unique=False)
    op.create_index(op.f('ix_collections_run_exception_invoice_id'), 'collections_run_exception', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_collections_run_exception_payment_id'), 'collections_run_exception', ['payment_id'], unique=False)
    op.create_index(op.f('ix_collections_run_exception_rule_code'), 'collections_run_exception', ['rule_code'], unique=False)
    op.create_index(op.f('ix_collections_run_exception_run_id'), 'collections_run_exception', ['run_id'], unique=False)
    op.create_table('collections_run_invoice_position',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('outstanding', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('is_overdue', sa.Boolean(), nullable=False),
    sa.Column('days_overdue', sa.Integer(), nullable=False),
    sa.Column('ageing_bucket', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['collections_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_run_invoice_position_customer_id'), 'collections_run_invoice_position', ['customer_id'], unique=False)
    op.create_index(op.f('ix_collections_run_invoice_position_invoice_id'), 'collections_run_invoice_position', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_collections_run_invoice_position_is_overdue'), 'collections_run_invoice_position', ['is_overdue'], unique=False)
    op.create_index(op.f('ix_collections_run_invoice_position_region'), 'collections_run_invoice_position', ['region'], unique=False)
    op.create_index(op.f('ix_collections_run_invoice_position_run_id'), 'collections_run_invoice_position', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collections_run_invoice_position_run_id'), table_name='collections_run_invoice_position')
    op.drop_index(op.f('ix_collections_run_invoice_position_region'), table_name='collections_run_invoice_position')
    op.drop_index(op.f('ix_collections_run_invoice_position_is_overdue'), table_name='collections_run_invoice_position')
    op.drop_index(op.f('ix_collections_run_invoice_position_invoice_id'), table_name='collections_run_invoice_position')
    op.drop_index(op.f('ix_collections_run_invoice_position_customer_id'), table_name='collections_run_invoice_position')
    op.drop_table('collections_run_invoice_position')
    op.drop_index(op.f('ix_collections_run_exception_run_id'), table_name='collections_run_exception')
    op.drop_index(op.f('ix_collections_run_exception_rule_code'), table_name='collections_run_exception')
    op.drop_index(op.f('ix_collections_run_exception_payment_id'), table_name='collections_run_exception')
    op.drop_index(op.f('ix_collections_run_exception_invoice_id'), table_name='collections_run_exception')
    op.drop_index(op.f('ix_collections_run_exception_customer_id'), table_name='collections_run_exception')
    op.drop_table('collections_run_exception')
    op.drop_index(op.f('ix_collections_run_event_stage'), table_name='collections_run_event')
    op.drop_index(op.f('ix_collections_run_event_run_id'), table_name='collections_run_event')
    op.drop_index(op.f('ix_collections_run_event_level'), table_name='collections_run_event')
    op.drop_table('collections_run_event')
    op.drop_index(op.f('ix_collections_run_status'), table_name='collections_run')
    op.drop_table('collections_run')
    # ### end Alembic commands ###
