"""add control gate fields to collections_run

Revision ID: 9329bf349219
Revises: 3c6653dbe726
Create Date: 2026-08-31 19:05:12.717818

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9329bf349219'
down_revision = '3c6653dbe726'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections_run', sa.Column('gate_threshold', sa.Numeric(precision=6, scale=4), nullable=True))
    op.add_column('collections_run', sa.Column('exception_row_rate', sa.Numeric(precision=6, scale=4), nullable=True))
    op.add_column('collections_run', sa.Column('distinct_invoices_affected', sa.Integer(), nullable=True))
    op.add_column('collections_run', sa.Column('distinct_invoice_rate', sa.Numeric(precision=6, scale=4), nullable=True))
    op.add_column('collections_run', sa.Column('narrative', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections_run', 'narrative')
    op.drop_column('collections_run', 'distinct_invoice_rate')
    op.drop_column('collections_run', 'distinct_invoices_affected')
    op.drop_column('collections_run', 'exception_row_rate')
    op.drop_column('collections_run', 'gate_threshold')
    # ### end Alembic commands ###
