"""add summary_source to collections_run

Revision ID: dd50d5d22c38
Revises: 9329bf349219
Create Date: 2026-08-31 19:16:21.767458

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'dd50d5d22c38'
down_revision = '9329bf349219'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections_run', sa.Column('summary_source', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections_run', 'summary_source')
    # ### end Alembic commands ###
