"""add collections_run_rule_explanation table

Revision ID: e323292b9464
Revises: dd50d5d22c38
Create Date: 2026-08-31 19:34:25.288824

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e323292b9464'
down_revision = 'dd50d5d22c38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections_run_rule_explanation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('rule_code', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('cause', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('impact', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('suggested_fix', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('auto_fixable', sa.Boolean(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['collections_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_run_rule_explanation_rule_code'), 'collections_run_rule_explanation', ['rule_code'], unique=False)
    op.create_index(op.f('ix_collections_run_rule_explanation_run_id'), 'collections_run_rule_explanation', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collections_run_rule_explanation_run_id'), table_name='collections_run_rule_explanation')
    op.drop_index(op.f('ix_collections_run_rule_explanation_rule_code'), table_name='collections_run_rule_explanation')
    op.drop_table('collections_run_rule_explanation')
    # ### end Alembic commands ###
