"""add stored_file_path to collections_run

Revision ID: ed5380647078
Revises: e323292b9464
Create Date: 2026-08-31 21:32:06.171741

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ed5380647078'
down_revision = 'e323292b9464'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections_run', sa.Column('stored_file_path', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections_run', 'stored_file_path')
    # ### end Alembic commands ###
