/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as CollectionsExceptionsRouteImport } from './routes/collections/exceptions'
import { Route as CollectionsMappingRouteImport } from './routes/collections/mapping'
import { Route as CollectionsRunDetailRouteImport } from './routes/collections/run-detail'
import { Route as CollectionsRunsRouteImport } from './routes/collections/runs'
import { Route as CollectionsSummaryRouteImport } from './routes/collections/summary'
import { Route as CollectionsUploadRouteImport } from './routes/collections/upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const CollectionsExceptionsRoute = CollectionsExceptionsRouteImport.update({
  id: '/collections/exceptions',
  path: '/collections/exceptions',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsMappingRoute = CollectionsMappingRouteImport.update({
  id: '/collections/mapping',
  path: '/collections/mapping',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRunDetailRoute = CollectionsRunDetailRouteImport.update({
  id: '/collections/run-detail',
  path: '/collections/run-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRunsRoute = CollectionsRunsRouteImport.update({
  id: '/collections/runs',
  path: '/collections/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSummaryRoute = CollectionsSummaryRouteImport.update({
  id: '/collections/summary',
  path: '/collections/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsUploadRoute = CollectionsUploadRouteImport.update({
  id: '/collections/upload',
  path: '/collections/upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/collections/exceptions': typeof CollectionsExceptionsRoute
  '/collections/mapping': typeof CollectionsMappingRoute
  '/collections/run-detail': typeof CollectionsRunDetailRoute
  '/collections/runs': typeof CollectionsRunsRoute
  '/collections/summary': typeof CollectionsSummaryRoute
  '/collections/upload': typeof CollectionsUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/collections/exceptions': typeof CollectionsExceptionsRoute
  '/collections/mapping': typeof CollectionsMappingRoute
  '/collections/run-detail': typeof CollectionsRunDetailRoute
  '/collections/runs': typeof CollectionsRunsRoute
  '/collections/summary': typeof CollectionsSummaryRoute
  '/collections/upload': typeof CollectionsUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/collections/exceptions': typeof CollectionsExceptionsRoute
  '/collections/mapping': typeof CollectionsMappingRoute
  '/collections/run-detail': typeof CollectionsRunDetailRoute
  '/collections/runs': typeof CollectionsRunsRoute
  '/collections/summary': typeof CollectionsSummaryRoute
  '/collections/upload': typeof CollectionsUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/settings'
    | '/collections/exceptions'
    | '/collections/mapping'
    | '/collections/run-detail'
    | '/collections/runs'
    | '/collections/summary'
    | '/collections/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/settings'
    | '/collections/exceptions'
    | '/collections/mapping'
    | '/collections/run-detail'
    | '/collections/runs'
    | '/collections/summary'
    | '/collections/upload'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/items'
    | '/_layout/settings'
    | '/collections/exceptions'
    | '/collections/mapping'
    | '/collections/run-detail'
    | '/collections/runs'
    | '/collections/summary'
    | '/collections/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  CollectionsExceptionsRoute: typeof CollectionsExceptionsRoute
  CollectionsMappingRoute: typeof CollectionsMappingRoute
  CollectionsRunDetailRoute: typeof CollectionsRunDetailRoute
  CollectionsRunsRoute: typeof CollectionsRunsRoute
  CollectionsSummaryRoute: typeof CollectionsSummaryRoute
  CollectionsUploadRoute: typeof CollectionsUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/collections/exceptions': {
      id: '/collections/exceptions'
      path: '/collections/exceptions'
      fullPath: '/collections/exceptions'
      preLoaderRoute: typeof CollectionsExceptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/mapping': {
      id: '/collections/mapping'
      path: '/collections/mapping'
      fullPath: '/collections/mapping'
      preLoaderRoute: typeof CollectionsMappingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/run-detail': {
      id: '/collections/run-detail'
      path: '/collections/run-detail'
      fullPath: '/collections/run-detail'
      preLoaderRoute: typeof CollectionsRunDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/runs': {
      id: '/collections/runs'
      path: '/collections/runs'
      fullPath: '/collections/runs'
      preLoaderRoute: typeof CollectionsRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/summary': {
      id: '/collections/summary'
      path: '/collections/summary'
      fullPath: '/collections/summary'
      preLoaderRoute: typeof CollectionsSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/upload': {
      id: '/collections/upload'
      path: '/collections/upload'
      fullPath: '/collections/upload'
      preLoaderRoute: typeof CollectionsUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  CollectionsExceptionsRoute: CollectionsExceptionsRoute,
  CollectionsMappingRoute: CollectionsMappingRoute,
  CollectionsRunDetailRoute: CollectionsRunDetailRoute,
  CollectionsRunsRoute: CollectionsRunsRoute,
  CollectionsSummaryRoute: CollectionsSummaryRoute,
  CollectionsUploadRoute: CollectionsUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
